/**
 * State Management Package
 *
 * Centralized state management using nanostores for cross-framework compatibility.
 * Used by both the Dashboard (Epic 9) and Game (Epic 10).
 */

// Types
export * from './types';

// Draft atoms and actions (Story 9-1-6 enhancements)
export {
  $drafts,
  $currentDraftId,
  $currentDraft,
  $draftsList,
  $draftsCount,
  $isAtMaxDrafts,
  $isSaving,
  $lastSavedAt,
  $saveError,
  $hasPendingChanges,
  createDraft,
  updateDraft,
  updateDraftDebounced,
  flushPendingSave,
  deleteDraft,
  setCurrentDraft,
  getDraft,
  getDraftForUser,
  getDraftsForUser,
  markSectionEdited,
  isSectionEdited,
  updateOutputSection,
  clearAllDrafts,
  clearSaveError,
  persistDraft,
  setupDraftsCrossTabSync,
  sortDrafts,
  filterDraftsBySearch,
  draftActions,
  DRAFT_SCHEMA_VERSION,
  MAX_DRAFTS,
  type DraftSort,
} from './atoms/drafts';

// Proposal atoms and actions (for mock/dev mode)
export {
  $proposals,
  $proposalsList,
  $activeProposals,
  $pastProposals,
  addProposal,
  getProposal,
  updateProposalStatus,
  addVote,
  clearAllProposals,
  type SubmittedProposal,
  type ProposalStatusType,
} from './atoms/proposals';

// Vote atoms and actions
export {
  $voteTallies,
  $userVotes,
  $pendingVotes,
  setVoteTally,
  getVoteTally,
  clearVoteTally,
  setUserVote,
  getUserVote,
  clearUserVote,
  setPendingVote,
  getPendingVote,
  clearPendingVote,
  hasPendingVote,
  clearAllPendingVotes,
  setupCrossTabSync,
  voteActions,
} from './atoms/votes';

// Proposal list atoms and actions (Story 9-1-3)
export {
  $proposalList,
  $proposalFilters,
  $proposalSort,
  $proposalPage,
  $proposalTotalCount,
  $proposalListLoading,
  $proposalListError,
  $proposalStatusCounts,
  $userVotedProposalIds,
  hasUserVoted,
  setProposalList,
  setProposalFilters,
  setProposalTotalCount,
  setProposalListLoading,
  setProposalListError,
  setProposalStatusCounts,
  updateFilters,
  toggleStatusFilter,
  clearAllFilters,
  clearSearch,
  setProposalSort,
  setProposalPage,
  nextPage,
  previousPage,
  initFromUrlParams,
  getUrlParams,
  setupProposalListCrossTabSync,
  proposalListActions,
} from './atoms/proposalList';

// Toast atoms and actions (Story 9-1-5)
export {
  $toasts,
  $visibleToasts,
  $toastCount,
  addToast,
  removeToast,
  clearAllToasts,
  updateToast,
  showSuccess,
  showError,
  showWarning,
  showInfo,
  toastActions,
  DEFAULT_TOAST_DURATION,
  MAX_VISIBLE_TOASTS,
  type Toast,
  type ToastType,
  type ToastAction,
  type ToastOptions,
} from './atoms/toasts';

// Notification atoms and actions (Story 9-1-7)
export {
  $notifications,
  $notificationPreferences,
  $lastSeenProposalId,
  $unreadCount,
  $visibleNotifications,
  $recentNotifications,
  $notificationSaveError,
  addNotification,
  markAsRead,
  markAllRead,
  removeNotification,
  clearNotifications,
  updateNotificationPreferences,
  resetNotificationPreferences,
  clearNotificationSaveError,
  getNotification,
  setupNotificationsCrossTabSync,
  createVoteResultNotification,
  createNewProposalNotification,
  createVotingDeadlineNotification,
  notificationActions,
  DEFAULT_PREFERENCES,
  PREFERENCES_SCHEMA_VERSION,
  MAX_NOTIFICATIONS,
  MAX_NOTIFICATIONS_PER_TYPE_PER_HOUR,
  type Notification,
  type NotificationType,
  type NotificationMetadata,
  type NotificationPreferences,
} from './atoms/notifications';

// Token balance atoms and actions (Story 9-2-1)
export {
  $tokenBalance,
  $tokenMetadata,
  $tokenBalanceLoading,
  $tokenBalanceError,
  $formattedBalance,
  $hasBalance,
  formatTokenAmount,
  parseTokenAmount,
  setTokenBalanceLoading,
  setTokenBalance,
  setTokenBalanceError,
  clearTokenBalance,
  updateTokenMetadata,
  getTokenBalanceValue,
  isBalanceStale,
  tokenBalanceActions,
  TOKEN_DECIMALS,
  TOKEN_SYMBOL,
  TOKEN_NAME,
  DEFAULT_TOKEN_METADATA,
  type TokenBalanceState,
  type TokenMetadata,
} from './atoms/tokenBalance';

// Treasury atoms and actions (Story 9-2-2)
export {
  $treasury,
  $treasuryLoading,
  $treasuryError,
  $hasTreasuryData,
  $treasuryBalance,
  $treasuryTransactions,
  $totalDomBalance,
  $totalIcpBalance,
  $formattedDomBalance,
  $formattedIcpBalance,
  $domFundAllocations,
  $icpFundAllocations,
  formatTimestamp,
  getTransactionTypeLabel,
  getTransactionTypeColor,
  setTreasuryLoading,
  setTreasuryData,
  setTreasuryError,
  clearTreasury,
  isTreasuryStale,
  getTreasuryBalance,
  treasuryActions,
  TREASURY_STALE_THRESHOLD_MS,
  type TreasuryState,
  type TreasuryBalance,
  type Transaction,
  type TransactionType,
  type FundAllocation,
} from './atoms/treasury';

// Burn donation atoms and actions (Story 9-2-3)
export {
  $burnPool,
  $burnExecution,
  $userBurnHistory,
  $burnPoolLoading,
  $burnPoolError,
  $hasBurnPoolData,
  $formattedTotalBurned,
  $isBurnPending,
  $isBurnSuccess,
  $burnExecutionError,
  $burnHistory,
  $confirmedBurns,
  $userTotalBurned,
  $formattedUserTotalBurned,
  $burnCount,
  setBurnPoolLoading,
  setBurnPoolData,
  setBurnPoolError,
  clearBurnPool,
  isBurnPoolStale,
  setBurnPending,
  setBurnSuccess,
  setBurnExecutionError,
  resetBurnExecution,
  addBurnRecord,
  updateBurnRecordStatus,
  removeBurnRecord,
  clearBurnHistory,
  getPendingBurnRecord,
  exportBurnHistoryCSV,
  validateBurnAmount,
  getMaxBurnAmount,
  generateBurnId,
  burnActions,
  BURN_POOL_STALE_THRESHOLD_MS,
  MIN_BURN_AMOUNT,
  BURN_TX_FEE_RESERVE,
  MAX_BURN_HISTORY_RECORDS,
  BURN_HISTORY_STORAGE_KEY,
  type LocalBurnRecord,
  type BurnRecordStatus,
  type BurnPool,
  type BurnState,
  type BurnExecutionState,
} from './atoms/burn';

// Escrow view atoms and actions (Story 9-2-4)
export {
  $escrow,
  $selectedEscrow,
  $escrowStatusFilter,
  $escrowLoading,
  $escrowError,
  $hasEscrowData,
  $userEscrows,
  $activeEscrows,
  $completedEscrows,
  $escrowCount,
  $activeEscrowCount,
  $totalEscrowedAmount,
  $totalReleasedAmount,
  $formattedTotalEscrowed,
  $formattedTotalReleased,
  $filteredEscrows,
  $escrowsByStatus,
  $escrowStatusCounts,
  setEscrowLoading,
  setUserEscrows,
  setEscrowError,
  clearEscrow,
  setSelectedEscrow,
  setEscrowStatusFilter,
  isEscrowStale,
  getMilestoneProgress,
  getRemainingAmount,
  formatEscrowAmount,
  formatEscrowDate,
  formatEscrowDateTime,
  isExpiringSoon,
  getEscrowStatusColor,
  getMilestoneStatusColor,
  escrowActions,
  ESCROW_STALE_THRESHOLD_MS,
  type Escrow,
  type Milestone,
  type EscrowStatus,
  type MilestoneStatus,
  type TokenType,
  type ReleaseAuthority,
  type EscrowState,
  type EscrowStatusFilter,
} from './atoms/escrow';

// Member directory atoms and actions (Story 9-3-1)
export {
  $memberDirectory,
  $selectedMember,
  $memberSearchQuery,
  $userVisibility,
  $memberLoading,
  $memberError,
  $hasMemberData,
  $allMembers,
  $memberCount,
  $currentPage,
  $totalPages,
  $filteredMembers,
  $filteredMemberCount,
  $membersByArchetype,
  $archetypeCounts,
  setMemberLoading,
  setMembers,
  setMemberError,
  setCurrentPage,
  clearMembers,
  setSelectedMember,
  setMemberSearchQuery,
  clearMemberSearch,
  setUserVisibility,
  isMemberDataStale,
  formatMemberSince,
  getArchetypeColor,
  getVisibilityLabel,
  getVisibilityDescription,
  getContactStatusColor,
  getInitials,
  memberActions,
  MEMBERS_PER_PAGE,
  MEMBER_STALE_THRESHOLD_MS,
  type MemberProfile,
  type Visibility,
  type Archetype,
  type ContactRequest,
  type ContactStatus,
  type MemberDirectoryState,
} from './atoms/members';

// Contact request atoms and actions (Story 9-3-1)
export {
  $contacts,
  $contactModalOpen,
  $contactRecipient,
  $contactsLoading,
  $contactsError,
  $pendingSent,
  $pendingReceived,
  $approvedContacts,
  $rejectedRequests,
  $pendingReceivedCount,
  getContactStatusForPrincipal,
  setContactsLoading,
  setContacts,
  addSentRequest,
  updateRequestStatus,
  setContactsError,
  clearContacts,
  openContactModal,
  closeContactModal,
  isContactsStale,
  contactActions,
  CONTACTS_STALE_THRESHOLD_MS,
  type ContactsState,
} from './atoms/contacts';

